"""add fields(admin: User, name_site:BoxPass)

Revision ID: 3865541b9611
Revises: 5083f1f86cb2
Create Date: 2025-12-22 10:44:42.707123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3865541b9611'
down_revision: Union[str, None] = '5083f1f86cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxpass', sa.Column('name_site', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    op.drop_column('boxpass', 'name_site')
    # ### end Alembic commands ###
